#!/usr/bin/env bash

set -e

mkdir -p /root/.ssh

if [ -f "/root/.ssh/id_rsa" ]
then
    echo "id_rsa found doing nothing"
else
    echo $PRIVATE_KEY > /root/.ssh/id_rsa
fi

chmod 600 /root/.ssh/id_rsa


if [ -f "/root/.ssh/known_hosts" ]
then
    echo "known_hosts found doing nothing"
else
    echo $KNOWN_HOSTS > /root/.ssh/known_hosts
fi

chmod 644 /root/.ssh/known_hosts